export enum ActionTypes {
  GET_USER = '[UPDATE USER] Get user',
  GET_USER_SUCCESS = '[UPDATE USER] Success in accepting user',
  GET_USER_FAILURE = '[UPDATE USER] Failure to receive user',
  UPDATE_USER = '[UPDATE USER] Updating users',
  UPDATE_USER_SUCCESS = '[UPDATE USER] Successful acceptance of the update by the user',
  UPDATE_USER_FAILURE = '[UPDATE USER] Unable to update user',
  CHANGE_PASSWORD = '[UPDATE USER] change passwor',
  CHANGE_PASSWORD_SUCCESS = '[UPDATE USER] Password change success',
  CHANGE_PASSWORD_FAILURE = '[UPDATE USER] Password change failure',
  GET_ALL_ROLES = '[UPDATE USER] get all roles',
  GET_ALL_ROLES_SUCCESS = '[UPDATE USER] get all roles successfully',
  GET_ALL_ROLES_FAILURE = '[UPDATE USER] get all roles failed',
  INSTALL_ROLE = '[UPDATE USER] install role',
  INSTALL_ROLE_SUCCESS = '[UPDATE USER] install role success',
  INSTALL_ROLE_FAILURE = '[UPDATE USER] install role failure',
  UNINSTALL_ROLE = '[UPDATE USER] uninstall role',
  UNINSTALL_ROLE_SUCCESS = '[UPDATE USER] uninstall role success',
  UNINSTALL_ROLE_FAILURE = '[UPDATE USER] uninstall role failure',
}
